[package]

name = "guilibrs"

version = "0.1.0"

edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
defer-lite = "1.0.0"
eval = "0.4.3"
sdl3 = { version = "0.14.4" }

